/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardMyEventsRouteImport } from './routes/_dashboard/my-events'
import { Route as DashboardEventsRouteImport } from './routes/_dashboard/events'
import { Route as DashboardAddEventsRouteImport } from './routes/_dashboard/add-events'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMyEventsRoute = DashboardMyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsRoute = DashboardEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAddEventsRoute = DashboardAddEventsRouteImport.update({
  id: '/add-events',
  path: '/add-events',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/add-events': typeof DashboardAddEventsRoute
  '/events': typeof DashboardEventsRoute
  '/my-events': typeof DashboardMyEventsRoute
  '/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/add-events': typeof DashboardAddEventsRoute
  '/events': typeof DashboardEventsRoute
  '/my-events': typeof DashboardMyEventsRoute
  '/': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_dashboard/add-events': typeof DashboardAddEventsRoute
  '/_dashboard/events': typeof DashboardEventsRoute
  '/_dashboard/my-events': typeof DashboardMyEventsRoute
  '/_dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/signup'
    | '/add-events'
    | '/events'
    | '/my-events'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/signup' | '/add-events' | '/events' | '/my-events' | '/'
  id:
    | '__root__'
    | '/_dashboard'
    | '/login'
    | '/signup'
    | '/_dashboard/add-events'
    | '/_dashboard/events'
    | '/_dashboard/my-events'
    | '/_dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/my-events': {
      id: '/_dashboard/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof DashboardMyEventsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/events': {
      id: '/_dashboard/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof DashboardEventsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/add-events': {
      id: '/_dashboard/add-events'
      path: '/add-events'
      fullPath: '/add-events'
      preLoaderRoute: typeof DashboardAddEventsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAddEventsRoute: typeof DashboardAddEventsRoute
  DashboardEventsRoute: typeof DashboardEventsRoute
  DashboardMyEventsRoute: typeof DashboardMyEventsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAddEventsRoute: DashboardAddEventsRoute,
  DashboardEventsRoute: DashboardEventsRoute,
  DashboardMyEventsRoute: DashboardMyEventsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
